name: mictest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  device_info_plus: ^9.1.0
  file_picker: ^10.1.9
  path: ^1.8.3
  http: ^1.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.3.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  flutter_local_notifications: ^17.2.1
  socket_io_client: ^3.1.2
  web_socket_channel: ^2.4.0
  uuid: ^4.5.1
  geolocator: ^14.0.0
  audio_service: ^0.18.18
  just_audio: ^0.9.36
  workmanager: ^0.6.0
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true